//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDOLPZZZ.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spravochnaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spravochnaya()
        {
            this.Ychetnai = new HashSet<Ychetnai>();
        }
    
        public int Kod_Predpriytie { get; set; }
        public string Naimenovani { get; set; }
        public string Adres { get; set; }
        public string FIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ychetnai> Ychetnai { get; set; }
    }
}
