//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDOLPZZZ.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ychetnai
    {
        public int Nomer_Zapisi { get; set; }
        public int Kod_Predpriytie { get; set; }
        public string Naimenovanit_Prodykcie { get; set; }
        public int Kolichestvo { get; set; }
        public int Cena { get; set; }
    
        public virtual Spravochnaya Spravochnaya { get; set; }
    }
}
